CREATE TABLE GBC_SCHEDULED_SEMAFOR
(
    JOB_NAME       VARCHAR(64)  NOT NULL,
    LOCK_UNTIL TIMESTAMP(3) NOT NULL,
    LOCKED_AT  TIMESTAMP(3) NOT NULL,
    LOCKED_BY  VARCHAR(255) NOT NULL,
    PRIMARY KEY (JOB_NAME)
);


-- always at the bottom commit
commit;
