--------------------------------------------------------
--  File created - Thursday-March-24-2022
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ADV_DETAILS_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "ADV_DETAILS_SEQ"  MINVALUE 519490 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 620880 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "ADV_DETAILS_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence ADV_EXPR_LOG_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "ADV_EXPR_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1342072 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "ADV_EXPR_LOG_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence ANALYSIS_PARAM_EXPR_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "ANALYSIS_PARAM_EXPR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "ANALYSIS_PARAM_EXPR_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence ANALYSIS_PARAM_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "ANALYSIS_PARAM_SEQ"  MINVALUE 95 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 146 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "ANALYSIS_PARAM_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence ANALYSIS_PARAM_TYPE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "ANALYSIS_PARAM_TYPE_SEQ"  MINVALUE 6 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "ANALYSIS_PARAM_TYPE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence ANALYSIS_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "ANALYSIS_SEQ"  MINVALUE 924797 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 3851979 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "ANALYSIS_SEQ" TO "DEVELOPER";
GRANT ALTER ON "ANALYSIS_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence AUTHORIZATION_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "AUTHORIZATION_SEQ"  MINVALUE 8011 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 8845 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "AUTHORIZATION_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence BUSINESS_UNIT_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "BUSINESS_UNIT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "BUSINESS_UNIT_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence COUNTRY_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "COUNTRY_SEQ"  MINVALUE 5 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 64 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "COUNTRY_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence DICTIONARY_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "DICTIONARY_SEQ"  MINVALUE 100050 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 109719 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "DICTIONARY_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence DICTIONARY_TABLE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "DICTIONARY_TABLE_SEQ"  MINVALUE 22 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 39 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "DICTIONARY_TABLE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence EMAIL_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "EMAIL_SEQ"  MINVALUE 88 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 8498 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "EMAIL_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence EVENT_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "EVENT_SEQ"  MINVALUE 14440 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 926064 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "EVENT_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence FORMULA_CALCULATION_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "FORMULA_CALCULATION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 780524 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "FORMULA_CALCULATION_SEQ" TO "DEVELOPER";
GRANT ALTER ON "FORMULA_CALCULATION_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence FUEL_TYPE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "FUEL_TYPE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "FUEL_TYPE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence GBC_LOAD_ANALYSIS_CHEMAT_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "GBC_LOAD_ANALYSIS_CHEMAT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 773 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence JOURNAL_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "JOURNAL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41252028 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "JOURNAL_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence LANDFILL_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "LANDFILL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 23 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "LANDFILL_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence LANGUAGE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "LANGUAGE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 126 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "LANGUAGE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence LOAD_QUANTITY_IARSOC_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "LOAD_QUANTITY_IARSOC_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2447386 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOGIN_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "LOGIN_SEQ"  MINVALUE 18834 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 690180 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "LOGIN_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence MATERIAL_CONVERSION_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "MATERIAL_CONVERSION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 806 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "MATERIAL_CONVERSION_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence MATERIAL_FL_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "MATERIAL_FL_SEQ"  MINVALUE 67 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1986 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "MATERIAL_FL_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence MATERIAL_MATERIAL_TYPE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "MATERIAL_MATERIAL_TYPE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 4485 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "MATERIAL_MATERIAL_TYPE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence MATERIAL_NODE_AP_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "MATERIAL_NODE_AP_SEQ"  MINVALUE 5437 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 16674 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "MATERIAL_NODE_AP_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence MATERIAL_NODE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "MATERIAL_NODE_SEQ"  MINVALUE 16034 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 18473 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "MATERIAL_NODE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence MATERIAL_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "MATERIAL_SEQ"  MINVALUE 34 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 3932 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "MATERIAL_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence MATERIAL_TYPE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "MATERIAL_TYPE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 282 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "MATERIAL_TYPE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence MENU_ROLE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "MENU_ROLE_SEQ"  MINVALUE 13564 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 13575 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "MENU_ROLE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence MENU_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "MENU_SEQ"  MINVALUE 421 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 449 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "MENU_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence METER_CALIBRATION_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "METER_CALIBRATION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 9 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "METER_CALIBRATION_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence METER_CERTIFICATE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "METER_CERTIFICATE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1522 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "METER_CERTIFICATE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence METER_CONVERSION_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "METER_CONVERSION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 79 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "METER_CONVERSION_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence METER_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "METER_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1045 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "METER_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence METER_TYPE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "METER_TYPE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 86 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "METER_TYPE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence METER_UNCERTAINTY_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "METER_UNCERTAINTY_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 955 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "METER_UNCERTAINTY_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence NODE_LEVEL_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "NODE_LEVEL_SEQ"  MINVALUE 7 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 18 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "NODE_LEVEL_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence NODE_PLANT_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "NODE_PLANT_SEQ"  MINVALUE 1514 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1514 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "NODE_PLANT_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence NODE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "NODE_SEQ"  MINVALUE 1511 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2117 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "NODE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence NODE_TYPES_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "NODE_TYPES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1947 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "NODE_TYPES_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence NODE_TYPE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "NODE_TYPE_SEQ"  MINVALUE 128 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 170 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "NODE_TYPE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence PRODUCTION_PLAN_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "PRODUCTION_PLAN_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 437 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "PRODUCTION_PLAN_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence PS_TXN_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "PS_TXN_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 50 START WITH 2051 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence QUANTITY_ANALYSIS_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "QUANTITY_ANALYSIS_SEQ"  MINVALUE 1432278 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 63968754 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "QUANTITY_ANALYSIS_SEQ" TO "DEVELOPER";
GRANT ALTER ON "QUANTITY_ANALYSIS_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence QUANTITY_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "QUANTITY_SEQ"  MINVALUE 1324248 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2205813 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "QUANTITY_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence REGION_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "REGION_SEQ"  MINVALUE 4 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 23 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "REGION_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence REPORTED_ISSUES_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "REPORTED_ISSUES_SEQ"  MINVALUE 350 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 454 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "REPORTED_ISSUES_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence REQUEST_LOG_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "REQUEST_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 454 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "REQUEST_LOG_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence SCOPE_ANALYSIS_PARAM_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "SCOPE_ANALYSIS_PARAM_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 4977 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "SCOPE_ANALYSIS_PARAM_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence SCOPE_DENOMINATOR_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "SCOPE_DENOMINATOR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 3056 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "SCOPE_DENOMINATOR_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence SCOPE_FUEL_SPEC_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "SCOPE_FUEL_SPEC_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 12 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "SCOPE_FUEL_SPEC_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence SCOPE_MATERIAL_NODE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "SCOPE_MATERIAL_NODE_SEQ"  MINVALUE 2999 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 30705 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "SCOPE_MATERIAL_NODE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence SCOPE_MATERIAL_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "SCOPE_MATERIAL_SEQ"  MINVALUE 2678 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 30705 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "SCOPE_MATERIAL_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence SCOPE_NODE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "SCOPE_NODE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 30705 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "SCOPE_NODE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence SCOPE_PROCESS_SPEC_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "SCOPE_PROCESS_SPEC_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 24 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "SCOPE_PROCESS_SPEC_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence SCOPE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "SCOPE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 3877 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "SCOPE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence SCOPE_TYPE_SPEC_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "SCOPE_TYPE_SPEC_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 15 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "SCOPE_TYPE_SPEC_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence UNIT_ANALYSIS_FORMAT_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "UNIT_ANALYSIS_FORMAT_SEQ"  MINVALUE 7 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "UNIT_ANALYSIS_FORMAT_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence UNIT_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "UNIT_SEQ"  MINVALUE 22 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 90 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "UNIT_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence UNIT_SET_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "UNIT_SET_SEQ"  MINVALUE 3 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "UNIT_SET_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence UNIT_SET_SETTINGS_AP_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "UNIT_SET_SETTINGS_AP_SEQ"  MINVALUE 188 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 950 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "UNIT_SET_SETTINGS_AP_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence UNIT_SET_SETTINGS_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "UNIT_SET_SETTINGS_SEQ"  MINVALUE 15 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 6444 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "UNIT_SET_SETTINGS_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence UNIT_TYPE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "UNIT_TYPE_SEQ"  MINVALUE 11 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 18 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "UNIT_TYPE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence USEPA_MATERIAL_TYPE_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "USEPA_MATERIAL_TYPE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 29 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "USEPA_MATERIAL_TYPE_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence USER_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "USER_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1336 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "USER_SEQ" TO "DEVELOPER";
--------------------------------------------------------
--  DDL for Sequence WEBSERVICES_SEQ
--------------------------------------------------------

CREATE SEQUENCE  "WEBSERVICES_SEQ"  MINVALUE 12339 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 680789 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "WEBSERVICES_SEQ" TO "DEVELOPER";

--------------------------------------------------------
--  DDL for Sequence DICTIONARY_UI_SEQ
--------------------------------------------------------
CREATE SEQUENCE  "DICTIONARY_UI_SEQ"  MINVALUE 3079 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 3079 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
GRANT SELECT ON "DICTIONARY_UI_SEQ" TO "DEVELOPER";
